"""empty message

Revision ID: 1fcf51be795e
Revises: 19cdaddb97ba
Create Date: 2023-02-07 14:53:59.428225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcf51be795e'
down_revision = '19cdaddb97ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('services_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['carer_id'], ['id'])
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('services_client_id_fkey', 'clients', ['client_id'], ['id'])
        batch_op.drop_column('carer_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('caption')
        batch_op.drop_column('alt')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
